=== ArtemHarchishin/masapi/trunk/masapiFileDependencies.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
            elementFormDefault="qualified">

            <xsd:element name="application">
                <xsd:complexType>
					<xsd:sequence maxOccurs="1" minOccurs="0">
                        <xsd:element name="variables" type="Variables" />
                    </xsd:sequence>
				
                    <xsd:sequence>
                        <xsd:element name="files" type="Files" />
                        <xsd:element name="dependencies" type="Dependencies" />
                    </xsd:sequence>
                </xsd:complexType>
            </xsd:element>
            
            <xsd:complexType name="Files">
                <xsd:choice maxOccurs="unbounded">
                	<xsd:element name="folder" type="FolderDefinition" />
                    <xsd:element name="file" type="FileDefinition" />
                </xsd:sequence>
                
                <xsd:attribute name="useCache" type="Boolean" />
                <xsd:attribute name="virtualBytesTotal" type="xsd:int" />
                <xsd:attribute name="basePath" type="xsd:string" />
            </xsd:complexType>
            
            <xsd:complexType name="FolderDefinition">
            	<xsd:choice maxOccurs="unbounded">
                	<xsd:element name="folder" type="FolderDefinition" />
                    <xsd:element name="file" type="FileDefinition" />
                </xsd:sequence>
                
                <xsd:attribute name="path" type="xsd:string" />
                <xsd:attribute name="absolutePath" type="Boolean" />
            </xsd:complexType>
            
            <xsd:complexType name="Dependencies">
                <xsd:choice maxOccurs="unbounded">
                    <xsd:element name="file" type="FileDependency" />
                    <xsd:element name="dependency" type="FileDependency" />
					<xsd:element name="group" type="FileDependency" />
                </xsd:choice>
            </xsd:complexType>
            
            <xsd:complexType name="FileDefinition">
            	<xsd:attribute name="url" type="xsd:string" use="required" />
                <xsd:attribute name="name" type="xsd:string" />
                <xsd:attribute name="type" type="FileType" />
                <xsd:attribute name="global" type="Boolean" />
                <xsd:attribute name="useCache" type="Boolean" />
                <xsd:attribute name="netStage" type="NetState" />
                <xsd:attribute name="virtualBytesTotal" type="xsd:int" />
                <xsd:attribute name="priority" type="xsd:int" />
                <xsd:attribute name="requestMethod" type="RequestMethod" />
                <xsd:attribute name="requestData" type="xsd:string" />
                
                <xsd:anyAttribute processContents="skip" />
            </xsd:complexType>
            
            <xsd:complexType name="FileDependency">
                <xsd:choice maxOccurs="unbounded">
                    <xsd:element name="file" type="FileDependency" />
                    <xsd:element name="dependency" type="FileDependency" />
					<xsd:element name="group" type="FileDependency" />
                </xsd:choice>
                
                <xsd:attribute name="name" type="xsd:string" use="required" />
            </xsd:complexType>
			
			<xsd:complexType name="Variables">
                <xsd:sequence maxOccurs="unbounded" minOccurs="0">
					<xsd:element name="var" type="Variable" />
				</xsd:sequence>
            </xsd:complexType>
			
			<xsd:complexType name="Variable" mixed="true">
                <xsd:attribute name="name" type="xsd:string" use="required" />
            </xsd:complexType>
            
            <xsd:simpleType name="Boolean">
                <xsd:restriction base="xsd:string">
                    <xsd:pattern value="true|false|yes|no|-?[0-9]+"/>
                </xsd:restriction>
            </xsd:simpleType>
            
            <xsd:simpleType name="FileType">
                <xsd:restriction base="xsd:string">
                    <xsd:pattern value="swf|text|variables|binary|sound|stream"/>
                </xsd:restriction>
            </xsd:simpleType>
            
            <xsd:simpleType name="NetState">
                <xsd:restriction base="xsd:string">
                    <xsd:pattern value="online|offline|dynamic"/>
                </xsd:restriction>
            </xsd:simpleType>
            
            <xsd:simpleType name="RequestMethod">
                <xsd:restriction base="xsd:string">
                    <xsd:pattern value="GET|POST"/>
                </xsd:restriction>
            </xsd:simpleType>
</xsd:schema>

=== ArtemHarchishin/masapi/trunk/samples/3.0 Application massloader/application.xml
<?xml version="1.0" encoding="utf-8" ?>
<application xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
             xsi:noNamespaceSchemaLocation="http://www.astorm.ch/masapi/masapiFileDependencies.xsd">
	<files>
		<file name="fonts" 	url="swf/fonts.swf" global="true" type="swf" 			virtualBytesTotal="35000" />
		<file name="menu"  	url="swf/menu.swf"  global="true" type="binary" 		virtualBytesTotal="20000" />
		<file name="menuData" 	url="data/menu.xml" 						virtualBytesTotal="2000" />
		<file name="menuMotion" url="data/menuMotion.xml" 					virtualBytesTotal="2000" />
		<file name="page1" 	url="swf/pages/page1.swf" 					virtualBytesTotal="5000" />
		<file name="page2" 	url="swf/pages/page2.swf" 					virtualBytesTotal="8000" />
		<file name="fontsTexte" url="swf/pages/fontsTexte.swf" type="swf" 			virtualBytesTotal="80000" />
		<file name="page1Texte" url="data/texte_page1.txt" type="variables" 			virtualBytesTotal="10000" />
		<file name="logoAdobe" 	url="data/adobe.png" type="swf" 				virtualBytesTotal="45000" />
		<file name="texteAdobe" url="data/titreAdobe.txt" type="text" 				virtualBytesTotal="2000" />
	</files>
	<dependencies>
		<file name="menu">
			<file name="menuMotion" />
			<file name="menuData" />
		</file>
		<file name="page1">
			<file name="fontsTexte" />
			<file name="page1Texte" />
		</file>
		<file name="page2">
			<file name="fontsTexte" />
			<file name="logoAdobe" />
			<file name="texteAdobe" />
		</file>
	</dependencies>
</application>
